### ISSUE TITLE
Clean subscribe termination

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#222] opened 2023-07-20 18:43 UTC
Currently, a subscriber will send SUBSCRIBE and the publisher will reply with SUBSCRIBE_OK/SUBSCRIBE_ERROR. It's undefined what a publisher should do when a broadcast/track is terminated after that.

A clean termination is especially problematic. I was under the assumption that they would send a SUBSCRIBE_ERROR with code=0. However, not only is this unstated in the draft, but it's introduces a race condition. There needs to be some way for the subscriber to wait until it received all of the content, such as a final object/group sequence, before the subscription is removed. This might also be problematic because relay can choose to not transmit objects/groups...

(my code errors pretty often because of this, since the catalog is a track with a single object that is closed immediately)

**Comment by fluffy** [comment] 2023-07-24 14:41
In some cases, a single subscription might get data for multiple tracks, so I think the right way to think about this is 1) have a way for client to know what the last object is for a given track and 2) client can then unsubscribe normal way. I phased it as "know what last object is" vs "steam ended" as I think that makes more sense for broader set of uses cases such as the one Luke has with the catalog at start of this issue.

**Comment by afrind** [comment] 2023-07-24 15:17
> a single subscription might get data for multiple tracks

Is that right?  SUBSCRIBE_REQUEST takes a Full Track Name so it should refer to a single track.

**Comment by kixelated** [comment] 2023-07-24 15:28
> This seems very similar to #203, but I may be missing a distinction?

Yeah looks like a duplicate.

**Comment by ianswett** [comment] 2023-07-24 15:35
There's a similar amount of discussion on both, so I'll close this as a dupe of #203

**Comment by fluffy** [comment] 2023-07-27 17:04
> > a single subscription might get data for multiple tracks
> 
> Is that right? SUBSCRIBE_REQUEST takes a Full Track Name so it should refer to a single track.

Just want to point I don't think that is the case. An SFU in a conferencing case needs to subscribe to all the input media and you want that aggregated not a zillion subscribes. 

That said, I do think this can all be discussed on the other bug

**Comment by afrind** [comment] 2023-07-27 19:00
@fluffy I'd recommend a separate issue for aggregating subscribes.

@suhasHere I see you reopened this issue, which was resolved as a duplicate.  Is there something unique to discuss here related to subscribe termination or can we keep the discussion in #203?

**Closed** 2023-10-04 20:40 UTC
Labels: Architectural, Subscribe
