### ISSUE TITLE
Relay failover support for subscribers and publishers

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#80] opened 2023-01-31 17:47 UTC
There is a need for subscribers and publishers to reconnect across relays with minimal state loss.

**Comment by kixelated** [comment] 2023-02-01 22:14
Yeah, that means limiting the amount of per-connection state. As was mentioned at lunch, we could still use something like QPACK to compress on a per-connection state, but stuff like the broadcast URN should be consistent across connections.

**Comment by afrind** [comment] 2023-05-05 20:19
I think this is a duplicate of #79, which is more generic (the reconnect problem applies to all publishers/subscribers and not just relays)

**Comment by afrind** [comment] 2023-05-05 20:20
Closed it too quickly, that issue is only about publishers.

**Comment by suhasHere** [comment] 2023-08-08 05:36
yes, this needs some handling in the transport

**Comment by ianswett** [comment] 2024-02-20 02:33
There are newer issues that discuss this in more detail, so closing this as a duplicate.

**Closed by ianswett** 2024-02-20 02:33 UTC
Labels: duplicate, Requirement
